name: buildPublish

on:
  push:
    branches: 
      - 'release/**'      

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  
  # TODO: Also add a step to automatically create a Github Release  
  publish:
    
    runs-on: windows-2019
    
    env:
      Publisher_Name: SajalVerma
      PAT: ${{ secrets.VS_MARKETPLACE_ACCESS_TOKEN }}
      Vs2019ToolsPath: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VSSDK\VisualStudioIntegration\Tools\Bin\'

    steps:
      
      - name: Login to marketplace
        shell : powershell
        run: |     
          $vsixPublisherTool = '${{ env.Vs2019ToolsPath }}' + 'VsixPublisher.exe'
          & $vsixPublisherTool login -publisherName $env:Publisher_Name -personalAccessToken $env:PAT
      
      - name: Publish to marketplace
        shell: powershell
        run: echo "TODO Publish to marketplace"
          
      - name: Logout of marketplace
        shell : powershell
        run: |
          $vsixPublisherTool = '${{ env.Vs2019ToolsPath }}' + 'VsixPublisher.exe'
          & $vsixPublisherTool logout -publisherName $env:Publisher_Name -ignoreMissingPublisher
          
    

