name: buildPublish

on:
  push:
    branches: 
      - 'release/**'      

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  
  # TODO: Also add a job to automatically create a Github Release  
  publish:
    
    runs-on: windows-2019
    
    env:
      Publisher_Name: SajalVerma
      PAT: ${{ secrets.VS_MARKETPLACE_ACCESS_TOKEN }}
      Vs2019ToolsPath: 'Microsoft Visual Studio\2019\Enterprise\VSSDK\VisualStudioIntegration\Tools\Bin\'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      - name: Login to marketplace
        shell : powershell
        # Access Program Files (x86) on Github runner via Powershell's $Env
        run: |
          $programFiles = $Env:ProgramFiles+'\'          
          $vsixPublisherTool = $programFiles + '${{ env.Vs2019ToolsPath }}' + 'VsixPublisher.exe'         
          & $vsixPublisher login -publisherName $env:Publisher_Name -personalAccessToken $env:PAT
          
      - name: Logout of marketplace
        shell : powershell
        run: |
          $programFiles = $Env:ProgramFiles+'\'          
          $vsixPublisherTool = $programFiles + '${{ env.Vs2019ToolsPath }}' + 'VsixPublisher.exe'
          & $vsixPublisher logout -publisherName $env:Publisher_Name -personalAccessToken $env:PAT
          
    

