name: dev-build

# Run this workflow on push to PRs and all branches except master.  
on:
  pull_request:
  workflow_dispatch:
    
jobs:

  build:

    runs-on: windows-latest

    env:
      Build_Version: 0.1.999                                    # Dummy version on PR artifact
      Solution_Name: src\GitBranchDiffer.sln                        
      Build_Configuration: Release
      Build_Platform: 'Any CPU'
      VSIX_Path: src\GitBranchDiffer\bin\Release\GitBranchDiffer.vsix
      

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload, probably not needed
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Update VSIX version in extension manifest
      shell: powershell
      run: .\build\VersionUpdater.ps1 $env:Build_Version

    # Restore the solution
    - name: Restore GitBranchDiffer
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Build_Configuration /v:m

    # Build the solution
    - name: Build GitBranchDiffer
      run: msbuild $env:Solution_Name /p:Configuration=$env:Build_Configuration /p:Platform=$env:Build_Platform /v:m

    # Upload the MSIX package: https://github.com/marketplace/actions/upload-artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: GitBranchDiffer-${{ env.Build_Version }}-Test
        path: ${{ env.VSIX_Path }}
